# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Drift < Formula
  desc "Terminal screensaver and ambient visualiser"
  homepage "https://github.com/phlx0/drift"
  version "1.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/phlx0/drift/releases/download/v1.1.0/drift_darwin_amd64.tar.gz"
      sha256 "97f8eb7f31a8c03bc528cef417357a342df7dbd9dce9326676de044d03ee49c7"

      define_method(:install) do
        bin.install "drift"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/phlx0/drift/releases/download/v1.1.0/drift_darwin_arm64.tar.gz"
      sha256 "4c14f1dcacb3542961f05649d24654b3a9d2cccdac57dff26e212215403d49c3"

      define_method(:install) do
        bin.install "drift"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/phlx0/drift/releases/download/v1.1.0/drift_linux_amd64.tar.gz"
      sha256 "756e7bf9c39bc95aed98c9d2ffb07d251ef8ca7932f2733378c29ba93c9242a4"
      define_method(:install) do
        bin.install "drift"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/phlx0/drift/releases/download/v1.1.0/drift_linux_arm64.tar.gz"
      sha256 "4449f0e26d4935894d38ab0d5e736eabc410890c941a80874ae79cc4019d2cda"
      define_method(:install) do
        bin.install "drift"
      end
    end
  end

  test do
    system "#{bin}/drift", "version"
  end
end
