# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Drift < Formula
  desc "Terminal screensaver and ambient visualiser"
  homepage "https://github.com/phlx0/drift"
  version "1.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/phlx0/drift/releases/download/v1.2.0/drift_darwin_amd64.tar.gz"
      sha256 "c944663f25f6a030521a8327a4751ade5403a8de54fc4bc6cc089a1e326addd2"

      define_method(:install) do
        bin.install "drift"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/phlx0/drift/releases/download/v1.2.0/drift_darwin_arm64.tar.gz"
      sha256 "4f3fe08604eeedde8ef149a5d777879943799668e9fb54480e084df35e66aeb1"

      define_method(:install) do
        bin.install "drift"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/phlx0/drift/releases/download/v1.2.0/drift_linux_amd64.tar.gz"
      sha256 "0315e1230f0a8cd1679b33a135a25ad537b08462a1e1c62d01388e90ac68b8b9"
      define_method(:install) do
        bin.install "drift"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/phlx0/drift/releases/download/v1.2.0/drift_linux_arm64.tar.gz"
      sha256 "64d73c6be06ddf639b61072e6b793c133f0c1c6088f4569f0d2ca8162d5f452b"
      define_method(:install) do
        bin.install "drift"
      end
    end
  end

  test do
    system "#{bin}/drift", "version"
  end
end
