# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Drift < Formula
  desc "Terminal screensaver and ambient visualiser"
  homepage "https://github.com/phlx0/drift"
  version "1.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/phlx0/drift/releases/download/v1.0.1/drift_darwin_amd64.tar.gz"
      sha256 "8e7e95e800e10aa0ea9f87e5b7ddfe02233cd06713804ec8dcea1201c3934b00"

      define_method(:install) do
        bin.install "drift"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/phlx0/drift/releases/download/v1.0.1/drift_darwin_arm64.tar.gz"
      sha256 "a946b6e8d0d281a8ff9e317eed0893344af99b808474e4711afb98a08f932982"

      define_method(:install) do
        bin.install "drift"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/phlx0/drift/releases/download/v1.0.1/drift_linux_amd64.tar.gz"
      sha256 "64c4831d0032d1c8c57880d84e96d1e6eccd36d208f46287082a1e3f2cabe306"
      define_method(:install) do
        bin.install "drift"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/phlx0/drift/releases/download/v1.0.1/drift_linux_arm64.tar.gz"
      sha256 "e59cb9d6dc7c6a26a59dad82394f63744cd106e70a80b9602b79192aa6917207"
      define_method(:install) do
        bin.install "drift"
      end
    end
  end

  test do
    system "#{bin}/drift", "version"
  end
end
